/* ========== resource/game-assets.js ==========
 * 游戏资源单一数据源（由 app.js 硬编码迁移而来，自动生成）。
 * 通过 window.妹神官_gameAssets 暴露统一查询 API。
 * 加载顺序：必须在 assetResolver.js 之后、app.js 之前。
 */
(function () {
  'use strict';

  // ---- 托莉娜立绘（分层结构，立绘渲染直接消费）----
  const tolinaSprites = {
    "L1_base": {
      "SockW-Nude": "https://files.catbox.moe/1pju7n.png",
      "SockW-P1": "https://files.catbox.moe/l9c5wy.png",
      "SockW-P2": "https://files.catbox.moe/wi07jf.png",
      "SockW-P3": "https://files.catbox.moe/dncgjq.png",
      "BareLeg": "https://files.catbox.moe/d876u2.png",
      "BareLegNude": "https://files.catbox.moe/dola5y.png",
      "NudeLeg-Maid": "https://files.catbox.moe/kapkqj.png",
      "SockB-Maid": "https://files.catbox.moe/uz92b2.png",
      "SockB-Nude": "https://files.catbox.moe/gk77d4.png",
      "SockB-P3": "https://files.catbox.moe/7aonpg.png",
      "SockB-P4": "https://files.catbox.moe/ahm5s7.png",
      "SockW-Maid": "https://files.catbox.moe/56jazo.png"
    },
    "L2_hair": {
      "HairB": "https://files.catbox.moe/wa9pv2.png",
      "HairW": "https://files.catbox.moe/x6ad8g.png"
    },
    "L3_expression": {
      "P1": {
        "msgk-noHeart": "https://files.catbox.moe/hieebq.png",
        "Nervous": "https://files.catbox.moe/qf4wfu.png",
        "Normal": "https://files.catbox.moe/cu7vso.png",
        "Okay": "https://files.catbox.moe/cby40r.png",
        "rebuke1": "https://files.catbox.moe/w14swb.png",
        "rebuke2": "https://files.catbox.moe/p92xhl.png",
        "Sad": "https://files.catbox.moe/39pivr.png",
        "Shock1": "https://files.catbox.moe/or5iqb.png",
        "Shock2": "https://files.catbox.moe/ibd9at.png",
        "Shock3": "https://files.catbox.moe/czs8ac.png",
        "Shock4": "https://files.catbox.moe/y03ot3.png",
        "Angry1": "https://files.catbox.moe/d0fokf.png",
        "Angry2": "https://files.catbox.moe/3zr8ta.png",
        "appalling": "https://files.catbox.moe/azi3jg.png",
        "Bitter": "https://files.catbox.moe/61uspm.png",
        "Cry": "https://files.catbox.moe/k4loi9.png",
        "Disappoint": "https://files.catbox.moe/nq07tu.png",
        "Evade1": "https://files.catbox.moe/kdq6og.png",
        "Evade2": "https://files.catbox.moe/dfpftv.png",
        "Focus": "https://files.catbox.moe/7w93ov.png",
        "Happy": "https://files.catbox.moe/gu1ko4.png",
        "KissWaiting": "https://files.catbox.moe/0rug96.png",
        "msgk": "https://files.catbox.moe/scwi77.png",
        "Shy1": "https://files.catbox.moe/alayor.png",
        "Shy2": "https://files.catbox.moe/1wfgwq.png",
        "Shy3": "https://files.catbox.moe/dyur1k.png",
        "Shy4": "https://files.catbox.moe/dfbp51.png",
        "Sigh": "https://files.catbox.moe/vech41.png",
        "Smile": "https://files.catbox.moe/afuxch.png",
        "Speechless": "https://files.catbox.moe/t4c2x5.png",
        "Stare": "https://files.catbox.moe/qhjk23.png",
        "Unhappy": "https://files.catbox.moe/gcjagn.png",
        "Worry1": "https://files.catbox.moe/teuaif.png",
        "Worry2": "https://files.catbox.moe/3ei6rz.png"
      },
      "P3": {
        "Angry1": "https://files.catbox.moe/0d7roj.png",
        "Angry2": "https://files.catbox.moe/6qs4uw.png",
        "appalling": "https://files.catbox.moe/ksqj1f.png",
        "Bitter": "https://files.catbox.moe/w6kl99.png",
        "Cry": "https://files.catbox.moe/6u1d85.png",
        "Disappoint": "https://files.catbox.moe/rv06e7.png",
        "Evade1": "https://files.catbox.moe/04ogaf.png",
        "Evade2": "https://files.catbox.moe/y2tb5y.png",
        "Focus": "https://files.catbox.moe/yg6ln7.png",
        "Happy": "https://files.catbox.moe/b4ahdb.png",
        "KissWaiting": "https://files.catbox.moe/7f4voy.png",
        "msgk": "https://files.catbox.moe/pqkdrc.png",
        "msgk-noHeart": "https://files.catbox.moe/cvc21p.png",
        "Nervous": "https://files.catbox.moe/hgsmob.png",
        "Normal": "https://files.catbox.moe/a0u712.png",
        "Okay": "https://files.catbox.moe/pwnsv0.png",
        "rebuke1": "https://files.catbox.moe/sbcoj2.png",
        "rebuke2": "https://files.catbox.moe/8sruf2.png",
        "Sad": "https://files.catbox.moe/w2t420.png",
        "Shock1": "https://files.catbox.moe/xnvgc6.png",
        "Shock2": "https://files.catbox.moe/zye4l8.png",
        "Shock3": "https://files.catbox.moe/d38pho.png",
        "Shock4": "https://files.catbox.moe/s6ewh1.png",
        "Shy1": "https://files.catbox.moe/box3th.png",
        "Shy2": "https://files.catbox.moe/0wswm4.png",
        "Shy3": "https://files.catbox.moe/r4ok5a.png",
        "Shy4": "https://files.catbox.moe/8fn3a0.png",
        "Sigh": "https://files.catbox.moe/3ms63a.png",
        "Smile": "https://files.catbox.moe/db8kko.png",
        "Speechless": "https://files.catbox.moe/wwu3jl.png",
        "Stare": "https://files.catbox.moe/2lr5vl.png",
        "Unhappy": "https://files.catbox.moe/vfo26g.png",
        "Worry1": "https://files.catbox.moe/lzgogu.png",
        "Worry2": "https://files.catbox.moe/wzn5zs.png"
      }
    },
    "L4_cloth": {
      "P1": "https://files.catbox.moe/eq7ii3.png",
      "P2": "https://files.catbox.moe/jpxfrs.png",
      "P3": "https://files.catbox.moe/cpic5l.png",
      "P4": "https://files.catbox.moe/xk684t.png",
      "Bath": "https://files.catbox.moe/z5zas0.png"
    },
    "L5_special": {
      "BlackFace": "https://files.catbox.moe/us2r9v.png",
      "Brush": "https://files.catbox.moe/q801ld.png",
      "MouthHair": "https://files.catbox.moe/v14c12.png",
      "Tear": "https://files.catbox.moe/f1j6cg.png"
    },
    "L6_shadow": {
      "P1": "https://files.catbox.moe/fw7xcp.png",
      "P2": "https://files.catbox.moe/s0rj8s.png",
      "P3": "https://files.catbox.moe/r7vrvy.png",
      "P4": "https://files.catbox.moe/kuwlis.png"
    },
    "L7_maid": {
      "L7Maid": "https://files.catbox.moe/wc6lrg.png"
    }
  };

  // ---- 间男立绘 ----
  const rivalMaleSprites = {
    "哈罗德": {
      "base": "https://files.catbox.moe/7twll8.png",
      "shade": "https://files.catbox.moe/x8isar.png"
    },
    "马蒂亚斯": {
      "base": "https://files.catbox.moe/b01so5.png",
      "shade": "https://files.catbox.moe/ebiiab.png"
    },
    "埃德加": {
      "base": "https://files.catbox.moe/087jch.png",
      "shade": "https://files.catbox.moe/jdrwzy.png"
    },
    "约书亚": {
      "base": "https://files.catbox.moe/jnorft.png",
      "shade": "https://files.catbox.moe/6grmtd.png"
    }
  };

  // ---- Hstatus 界面资源 ----
  const hstatusAssets = {
    "outerBg": "https://files.catbox.moe/3jrv5v.png",
    "outerMain": "https://files.catbox.moe/iaar1p.png",
    "outerHighlight": "https://files.catbox.moe/e7e84g.png",
    "frame": "https://files.catbox.moe/lht9hm.png",
    "innerBg": "https://files.catbox.moe/92wfb8.png",
    "innerFg": "https://files.catbox.moe/lbxw3t.png",
    "innerHighlight": "https://files.catbox.moe/dm2rck.png",
    "cursor": "https://files.catbox.moe/dgdqmk.png",
    "exitBtn": "https://files.catbox.moe/fcyjir.png"
  };
  const cumUrls = {
    "chestLittle": "https://files.catbox.moe/htr1dh.png",
    "chestMuch": "https://files.catbox.moe/sct15g.png",
    "bellyLittle": "https://files.catbox.moe/1qk8mk.png",
    "bellyMuch": "https://files.catbox.moe/iznrta.png",
    "legLittle": "https://files.catbox.moe/j8g4g4.png",
    "legMuch": "https://files.catbox.moe/ay6ljp.png"
  };
  const wombPopupUrls = [
    "https://files.catbox.moe/q6u20q.png",
    "https://files.catbox.moe/9nv2qy.png",
    "https://files.catbox.moe/d166xy.png",
    "https://files.catbox.moe/8blqgc.png",
    "https://files.catbox.moe/p9r91i.png"
  ];

  // ---- Hstatus 立绘穿搭矩阵（服装×阶段）----
  const hstatusOutfits = {
    "女仆装": {
      "clothes": {
        "1-2": "https://files.catbox.moe/42fqqz.png",
        "3-4": "https://files.catbox.moe/y8qk8b.png"
      },
      "body": {
        "1-2": "https://files.catbox.moe/hbwlvs.png",
        "3-4": "https://files.catbox.moe/2nisdk.png"
      }
    },
    "常服": {
      "clothes": "https://files.catbox.moe/8dussi.png"
    },
    "暴露常服": {
      "clothes": "https://files.catbox.moe/ft5fz7.png"
    },
    "魅魔常服": {
      "clothes": "https://files.catbox.moe/4uv97f.png"
    },
    "魔王服": {
      "clothes": "https://files.catbox.moe/goz9h9.png"
    },
    "浴巾": {
      "clothes": "https://files.catbox.moe/z5zas0.png"
    }
  };
  const hstatusBodyByStage = {
    "1": "https://files.catbox.moe/9og146.png",
    "2": "https://files.catbox.moe/330l0g.png",
    "3": "https://files.catbox.moe/l9h2lz.png",
    "4": "https://files.catbox.moe/6qamux.png"
  };
  // ---- 菜单界面托莉娜立绘（按堕落阶段）----
  const menuSpriteByStage = {
    "1": "https://files.catbox.moe/xrfvzg.png",
    "2": "https://files.catbox.moe/md0p61.png",
    "3": "https://files.catbox.moe/5utwfz.png",
    "4": "https://files.catbox.moe/4ro2io.png"
  };
  // ---- 时间/天气图片 ----
  const timeImageMap = {
    "早": "https://files.catbox.moe/m3l95j.png",
    "中": "https://files.catbox.moe/xnzc7c.png",
    "晚": "https://files.catbox.moe/g2x21l.png",
    "夜": "https://files.catbox.moe/1iepv7.png",
    "午夜": "https://files.catbox.moe/p326lj.png"
  };
  const weatherImageMap = {
    "rainDay": "https://files.catbox.moe/d555se.png",
    "rainNight": "https://files.catbox.moe/s66j1n.png"
  };
  // ---- 游戏界面 UI 资源 ----
  const uiAssets = {
    "cursor": "https://files.catbox.moe/dgdqmk.png",
    "menuBg": "https://files.catbox.moe/ogteua.png",
    "menuBorder": "https://files.catbox.moe/gdyovq.png",
    "fullscreenBtn": "https://files.catbox.moe/wj2c68.png",
    "menuBtn": "https://files.catbox.moe/fcyjir.png",
    "menuExitBtn": "https://files.catbox.moe/hkgfil.png",
    "menuSettingsUI": "https://files.catbox.moe/dykagy.png",
    "settingsLabel": "https://files.catbox.moe/3fc4yw.png",
    "menuHstatusUI": "https://files.catbox.moe/yayh3o.png",
    "hstatusLabel": "https://files.catbox.moe/zj7251.png",
    "menuMapUI": "https://files.catbox.moe/n3kdfi.png",
    "mapLabel": "https://files.catbox.moe/vpyzz7.png",
    "menuHistoryUI": "https://files.catbox.moe/v0cbzh.png",
    "historyLabel": "https://files.catbox.moe/y9656v.png",
    "menuSaveUI": "https://files.catbox.moe/l143y2.png",
    "saveLabel": "https://files.catbox.moe/aiw7z8.png",
    "corruptionBar": "https://files.catbox.moe/fc42vd.png",
    "lustBar": "https://files.catbox.moe/g5wizu.png",
    "timeBack": "https://files.catbox.moe/buwqmc.png",
    "leftCover": "https://files.catbox.moe/t34ltk.png",
    "loadingLogo": "https://files.catbox.moe/39yn6v.png"
  };

  // ---- 预加载扁平清单（category: 系统/立绘/背景/CG/Hstatus）----
  const preloadList = [
    { name: "托莉娜立绘-L1-SockW-Nude", url: "https://files.catbox.moe/1pju7n.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L1-SockW-P1", url: "https://files.catbox.moe/l9c5wy.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L1-SockW-P2", url: "https://files.catbox.moe/wi07jf.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L1-SockW-P3", url: "https://files.catbox.moe/dncgjq.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L1-BareLeg", url: "https://files.catbox.moe/d876u2.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L1-BareLegNude", url: "https://files.catbox.moe/dola5y.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L1-NudeLeg-Maid", url: "https://files.catbox.moe/kapkqj.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L1-SockB-Maid", url: "https://files.catbox.moe/uz92b2.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L1-SockB-Nude", url: "https://files.catbox.moe/gk77d4.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L1-SockB-P3", url: "https://files.catbox.moe/7aonpg.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L1-SockB-P4", url: "https://files.catbox.moe/ahm5s7.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L1-SockW-Maid", url: "https://files.catbox.moe/56jazo.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L2-HairB", url: "https://files.catbox.moe/wa9pv2.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L2-HairW", url: "https://files.catbox.moe/x6ad8g.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P1-msgk-noHeart", url: "https://files.catbox.moe/hieebq.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P1-Nervous", url: "https://files.catbox.moe/qf4wfu.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P1-Normal", url: "https://files.catbox.moe/cu7vso.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P1-Okay", url: "https://files.catbox.moe/cby40r.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P1-rebuke1", url: "https://files.catbox.moe/w14swb.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P1-rebuke2", url: "https://files.catbox.moe/p92xhl.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P1-Sad", url: "https://files.catbox.moe/39pivr.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P1-Shock1", url: "https://files.catbox.moe/or5iqb.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P1-Shock2", url: "https://files.catbox.moe/ibd9at.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P1-Shock3", url: "https://files.catbox.moe/czs8ac.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P1-Shock4", url: "https://files.catbox.moe/y03ot3.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P1-Angry1", url: "https://files.catbox.moe/d0fokf.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P1-Angry2", url: "https://files.catbox.moe/3zr8ta.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P1-appalling", url: "https://files.catbox.moe/azi3jg.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P1-Bitter", url: "https://files.catbox.moe/61uspm.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P1-Cry", url: "https://files.catbox.moe/k4loi9.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P1-Disappoint", url: "https://files.catbox.moe/nq07tu.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P1-Evade1", url: "https://files.catbox.moe/kdq6og.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P1-Evade2", url: "https://files.catbox.moe/dfpftv.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P1-Focus", url: "https://files.catbox.moe/7w93ov.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P1-Happy", url: "https://files.catbox.moe/gu1ko4.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P1-KissWaiting", url: "https://files.catbox.moe/0rug96.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P1-msgk", url: "https://files.catbox.moe/scwi77.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P1-Shy1", url: "https://files.catbox.moe/alayor.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P1-Shy2", url: "https://files.catbox.moe/1wfgwq.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P1-Shy3", url: "https://files.catbox.moe/dyur1k.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P1-Shy4", url: "https://files.catbox.moe/dfbp51.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P1-Sigh", url: "https://files.catbox.moe/vech41.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P1-Smile", url: "https://files.catbox.moe/afuxch.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P1-Speechless", url: "https://files.catbox.moe/t4c2x5.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P1-Stare", url: "https://files.catbox.moe/qhjk23.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P1-Unhappy", url: "https://files.catbox.moe/gcjagn.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P1-Worry1", url: "https://files.catbox.moe/teuaif.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P1-Worry2", url: "https://files.catbox.moe/3ei6rz.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P3-Angry1", url: "https://files.catbox.moe/0d7roj.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P3-Angry2", url: "https://files.catbox.moe/6qs4uw.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P3-appalling", url: "https://files.catbox.moe/ksqj1f.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P3-Bitter", url: "https://files.catbox.moe/w6kl99.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P3-Cry", url: "https://files.catbox.moe/6u1d85.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P3-Disappoint", url: "https://files.catbox.moe/rv06e7.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P3-Evade1", url: "https://files.catbox.moe/04ogaf.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P3-Evade2", url: "https://files.catbox.moe/y2tb5y.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P3-Focus", url: "https://files.catbox.moe/yg6ln7.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P3-Happy", url: "https://files.catbox.moe/b4ahdb.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P3-KissWaiting", url: "https://files.catbox.moe/7f4voy.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P3-msgk", url: "https://files.catbox.moe/pqkdrc.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P3-msgk-noHeart", url: "https://files.catbox.moe/cvc21p.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P3-Nervous", url: "https://files.catbox.moe/hgsmob.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P3-Normal", url: "https://files.catbox.moe/a0u712.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P3-Okay", url: "https://files.catbox.moe/pwnsv0.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P3-rebuke1", url: "https://files.catbox.moe/sbcoj2.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P3-rebuke2", url: "https://files.catbox.moe/8sruf2.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P3-Sad", url: "https://files.catbox.moe/w2t420.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P3-Shock1", url: "https://files.catbox.moe/xnvgc6.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P3-Shock2", url: "https://files.catbox.moe/zye4l8.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P3-Shock3", url: "https://files.catbox.moe/d38pho.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P3-Shock4", url: "https://files.catbox.moe/s6ewh1.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P3-Shy1", url: "https://files.catbox.moe/box3th.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P3-Shy2", url: "https://files.catbox.moe/0wswm4.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P3-Shy3", url: "https://files.catbox.moe/r4ok5a.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P3-Shy4", url: "https://files.catbox.moe/8fn3a0.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P3-Sigh", url: "https://files.catbox.moe/3ms63a.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P3-Smile", url: "https://files.catbox.moe/db8kko.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P3-Speechless", url: "https://files.catbox.moe/wwu3jl.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P3-Stare", url: "https://files.catbox.moe/2lr5vl.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P3-Unhappy", url: "https://files.catbox.moe/vfo26g.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P3-Worry1", url: "https://files.catbox.moe/lzgogu.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L3-P3-Worry2", url: "https://files.catbox.moe/wzn5zs.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L4-P1", url: "https://files.catbox.moe/eq7ii3.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L4-P2", url: "https://files.catbox.moe/jpxfrs.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L4-P3", url: "https://files.catbox.moe/cpic5l.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L4-P4", url: "https://files.catbox.moe/xk684t.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L4-Bath", url: "https://files.catbox.moe/z5zas0.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L5-BlackFace", url: "https://files.catbox.moe/us2r9v.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L5-Brush", url: "https://files.catbox.moe/q801ld.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L5-MouthHair", url: "https://files.catbox.moe/v14c12.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L5-Tear", url: "https://files.catbox.moe/f1j6cg.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L6-P1", url: "https://files.catbox.moe/fw7xcp.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L6-P2", url: "https://files.catbox.moe/s0rj8s.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L6-P3", url: "https://files.catbox.moe/r7vrvy.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L6-P4", url: "https://files.catbox.moe/kuwlis.png", category: "立绘", type: "image" },
    { name: "托莉娜立绘-L7-L7Maid", url: "https://files.catbox.moe/wc6lrg.png", category: "立绘", type: "image" },
    { name: "间男立绘-哈罗德-本体", url: "https://files.catbox.moe/7twll8.png", category: "立绘", type: "image" },
    { name: "间男立绘-哈罗德-阴影", url: "https://files.catbox.moe/x8isar.png", category: "立绘", type: "image" },
    { name: "间男立绘-马蒂亚斯-本体", url: "https://files.catbox.moe/b01so5.png", category: "立绘", type: "image" },
    { name: "间男立绘-马蒂亚斯-阴影", url: "https://files.catbox.moe/ebiiab.png", category: "立绘", type: "image" },
    { name: "间男立绘-埃德加-本体", url: "https://files.catbox.moe/087jch.png", category: "立绘", type: "image" },
    { name: "间男立绘-埃德加-阴影", url: "https://files.catbox.moe/jdrwzy.png", category: "立绘", type: "image" },
    { name: "间男立绘-约书亚-本体", url: "https://files.catbox.moe/jnorft.png", category: "立绘", type: "image" },
    { name: "间男立绘-约书亚-阴影", url: "https://files.catbox.moe/6grmtd.png", category: "立绘", type: "image" },
    { name: "背景视频", url: "https://files.catbox.moe/2d1g4v.webm", category: "系统", type: "video" },
    { name: "标题Logo", url: "https://files.catbox.moe/ycywe2.png", category: "系统", type: "image" },
    { name: "New Game按钮", url: "https://files.catbox.moe/6ov4dt.png", category: "系统", type: "image" },
    { name: "Continue按钮", url: "https://files.catbox.moe/w6x4qd.png", category: "系统", type: "image" },
    { name: "Option按钮", url: "https://files.catbox.moe/1qixsh.png", category: "系统", type: "image" },
    { name: "CC协议图标", url: "https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1", category: "系统", type: "image" },
    { name: "BY协议图标", url: "https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1", category: "系统", type: "image" },
    { name: "NC协议图标", url: "https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1", category: "系统", type: "image" },
    { name: "SA协议图标", url: "https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1", category: "系统", type: "image" },
    { name: "Afternoon", url: "https://files.catbox.moe/g2x21l.png", category: "系统", type: "image" },
    { name: "Midnight", url: "https://files.catbox.moe/p326lj.png", category: "系统", type: "image" },
    { name: "Morning", url: "https://files.catbox.moe/m3l95j.png", category: "系统", type: "image" },
    { name: "Night", url: "https://files.catbox.moe/1iepv7.png", category: "系统", type: "image" },
    { name: "Noon", url: "https://files.catbox.moe/xnzc7c.png", category: "系统", type: "image" },
    { name: "rainDay", url: "https://files.catbox.moe/d555se.png", category: "系统", type: "image" },
    { name: "rainNight", url: "https://files.catbox.moe/s66j1n.png", category: "系统", type: "image" },
    { name: "LeftCover", url: "https://files.catbox.moe/t34ltk.png", category: "系统", type: "image" },
    { name: "TimeBack", url: "https://files.catbox.moe/buwqmc.png", category: "系统", type: "image" },
    { name: "Message_name", url: "https://files.catbox.moe/exeh4l.png", category: "系统", type: "image" },
    { name: "Message_Under", url: "https://files.catbox.moe/87622v.png", category: "系统", type: "image" },
    { name: "菜单界面背景", url: "https://files.catbox.moe/ogteua.png", category: "系统", type: "image" },
    { name: "菜单界面前景边框", url: "https://files.catbox.moe/gdyovq.png", category: "系统", type: "image" },
    { name: "金币背景框", url: "https://files.catbox.moe/eu5cai.png", category: "系统", type: "image" },
    { name: "堕落值变量条", url: "https://files.catbox.moe/knxts0.png", category: "系统", type: "image" },
    { name: "性欲值变量条", url: "https://files.catbox.moe/40v6og.png", category: "系统", type: "image" },
    { name: "Intro遮罩背景", url: "https://files.catbox.moe/dtbqcz.png", category: "系统", type: "image" },
    { name: "设置界面背景", url: "https://files.catbox.moe/e5v3lc.png", category: "系统", type: "image" },
    { name: "关闭按钮", url: "https://files.catbox.moe/hkgfil.png", category: "系统", type: "image" },
    { name: "按钮通用背景", url: "https://files.catbox.moe/8b71o8.png", category: "系统", type: "image" },
    { name: "存档项背景", url: "https://files.catbox.moe/9kmauu.png", category: "系统", type: "image" },
    { name: "加载Logo", url: "https://files.catbox.moe/j17ccs.png", category: "系统", type: "image" },
    { name: "全屏按钮", url: "https://files.catbox.moe/wj2c68.png", category: "系统", type: "image" },
    { name: "对话背景", url: "https://files.catbox.moe/z8wdof.png", category: "系统", type: "image" },
    { name: "CG画框", url: "https://files.catbox.moe/0o6yij.png", category: "系统", type: "image" },
    { name: "纯爱路线", url: "https://files.catbox.moe/wcejcp.jpg", category: "系统", type: "image" },
    { name: "游戏路线", url: "https://files.catbox.moe/s0how3.jpg", category: "系统", type: "image" },
    { name: "白天露天废墟", url: "https://files.catbox.moe/dswunx.png", category: "背景", type: "image" },
    { name: "白天露天长廊", url: "https://files.catbox.moe/qj6dcy.png", category: "背景", type: "image" },
    { name: "草地", url: "https://files.catbox.moe/y4spym.png", category: "背景", type: "image" },
    { name: "草地小路", url: "https://files.catbox.moe/uzpt5x.png", category: "背景", type: "image" },
    { name: "打开大门传送门走廊", url: "https://files.catbox.moe/el5ch1.png", category: "背景", type: "image" },
    { name: "地下建筑内", url: "https://files.catbox.moe/mevkx3.png", category: "背景", type: "image" },
    { name: "毒沼泽", url: "https://files.catbox.moe/rlv186.png", category: "背景", type: "image" },
    { name: "废墟", url: "https://files.catbox.moe/f9yq6v.png", category: "背景", type: "image" },
    { name: "关闭大门走廊", url: "https://files.catbox.moe/wp1iky.png", category: "背景", type: "image" },
    { name: "旱地", url: "https://files.catbox.moe/7pzktn.png", category: "背景", type: "image" },
    { name: "黑暗洞穴", url: "https://files.catbox.moe/2arfp5.png", category: "背景", type: "image" },
    { name: "黑森林", url: "https://files.catbox.moe/myr71d.png", category: "背景", type: "image" },
    { name: "荒地", url: "https://files.catbox.moe/ltnpnb.png", category: "背景", type: "image" },
    { name: "荒芜草地", url: "https://files.catbox.moe/fwuzgm.png", category: "背景", type: "image" },
    { name: "黄昏露天长廊", url: "https://files.catbox.moe/zyu55x.png", category: "背景", type: "image" },
    { name: "集市", url: "https://files.catbox.moe/o3rikj.png", category: "背景", type: "image" },
    { name: "建筑内", url: "https://files.catbox.moe/35n6q8.png", category: "背景", type: "image" },
    { name: "矿坑", url: "https://files.catbox.moe/ylkodm.png", category: "背景", type: "image" },
    { name: "矿坑2", url: "https://files.catbox.moe/lx6625.png", category: "背景", type: "image" },
    { name: "矿坑3", url: "https://files.catbox.moe/ec996u.png", category: "背景", type: "image" },
    { name: "魔界废土", url: "https://files.catbox.moe/g5834r.png", category: "背景", type: "image" },
    { name: "木地板", url: "https://files.catbox.moe/lcuxzp.png", category: "背景", type: "image" },
    { name: "熔岩地", url: "https://files.catbox.moe/np1np8.png", category: "背景", type: "image" },
    { name: "沙漠", url: "https://files.catbox.moe/8odtak.png", category: "背景", type: "image" },
    { name: "山路", url: "https://files.catbox.moe/cc3k6f.png", category: "背景", type: "image" },
    { name: "石制室内", url: "https://files.catbox.moe/dpbk63.png", category: "背景", type: "image" },
    { name: "石制室内2", url: "https://files.catbox.moe/37b3nb.png", category: "背景", type: "image" },
    { name: "树林小路", url: "https://files.catbox.moe/gungox.png", category: "背景", type: "image" },
    { name: "透光矿坑", url: "https://files.catbox.moe/x2zkz3.png", category: "背景", type: "image" },
    { name: "晚上露天长廊", url: "https://files.catbox.moe/crmevj.png", category: "背景", type: "image" },
    { name: "小镇路", url: "https://files.catbox.moe/xwhu4i.png", category: "背景", type: "image" },
    { name: "雪地", url: "https://files.catbox.moe/cvh6io.png", category: "背景", type: "image" },
    { name: "岩浆地", url: "https://files.catbox.moe/woqe7c.png", category: "背景", type: "image" },
    { name: "依山小路", url: "https://files.catbox.moe/rutz1i.png", category: "背景", type: "image" },
    { name: "阴天露天废墟", url: "https://files.catbox.moe/bwwhmr.png", category: "背景", type: "image" },
    { name: "矿坑4", url: "https://files.catbox.moe/arv06v.png", category: "背景", type: "image" },
    { name: "林中小径", url: "https://files.catbox.moe/x73t54.png", category: "背景", type: "image" },
    { name: "迷雾废墟", url: "https://files.catbox.moe/g4auhb.png", category: "背景", type: "image" },
    { name: "迷雾黑森林", url: "https://files.catbox.moe/yec24e.png", category: "背景", type: "image" },
    { name: "明亮洞穴", url: "https://files.catbox.moe/wq3zhj.png", category: "背景", type: "image" },
    { name: "荧光路", url: "https://files.catbox.moe/hd5ruw.png", category: "背景", type: "image" },
    { name: "云上", url: "https://files.catbox.moe/54ar1p.png", category: "背景", type: "image" },
    { name: "傍晚广场", url: "https://files.catbox.moe/ynxgez.png", category: "背景", type: "image" },
    { name: "傍晚教廷门口", url: "https://files.catbox.moe/l52u8s.png", category: "背景", type: "image" },
    { name: "城垛", url: "https://files.catbox.moe/31a6mq.png", category: "背景", type: "image" },
    { name: "城墙外", url: "https://files.catbox.moe/ahpe9q.png", category: "背景", type: "image" },
    { name: "房屋", url: "https://files.catbox.moe/4c2r5u.png", category: "背景", type: "image" },
    { name: "风暴海湾", url: "https://files.catbox.moe/bwxni5.png", category: "背景", type: "image" },
    { name: "海湾", url: "https://files.catbox.moe/n0e4jq.png", category: "背景", type: "image" },
    { name: "黄昏庄园门口", url: "https://files.catbox.moe/e6glwy.png", category: "背景", type: "image" },
    { name: "教堂", url: "https://files.catbox.moe/4rsj5z.png", category: "背景", type: "image" },
    { name: "教堂讲台", url: "https://files.catbox.moe/rf3kfk.png", category: "背景", type: "image" },
    { name: "教堂门口", url: "https://files.catbox.moe/31xlvk.png", category: "背景", type: "image" },
    { name: "客厅", url: "https://files.catbox.moe/g0tnbr.png", category: "背景", type: "image" },
    { name: "客厅晚上", url: "https://files.catbox.moe/7cgt32.png", category: "背景", type: "image" },
    { name: "石制走廊", url: "https://files.catbox.moe/dkenm7.png", category: "背景", type: "image" },
    { name: "无光教堂", url: "https://files.catbox.moe/ct4o7h.png", category: "背景", type: "image" },
    { name: "夜晚房屋", url: "https://files.catbox.moe/oa0wch.png", category: "背景", type: "image" },
    { name: "夜晚广场", url: "https://files.catbox.moe/03sg96.png", category: "背景", type: "image" },
    { name: "夜晚海湾", url: "https://files.catbox.moe/dmbv2v.png", category: "背景", type: "image" },
    { name: "夜晚教堂", url: "https://files.catbox.moe/ku7x1b.png", category: "背景", type: "image" },
    { name: "夜晚教堂门口", url: "https://files.catbox.moe/fu80fn.png", category: "背景", type: "image" },
    { name: "夜晚酒馆", url: "https://files.catbox.moe/7lhf43.png", category: "背景", type: "image" },
    { name: "树林", url: "https://files.catbox.moe/7fw6se.png", category: "背景", type: "image" },
    { name: "水潭", url: "https://files.catbox.moe/rjfcof.png", category: "背景", type: "image" },
    { name: "王宫花园", url: "https://files.catbox.moe/j29gf4.png", category: "背景", type: "image" },
    { name: "王宫走廊", url: "https://files.catbox.moe/05h0qs.png", category: "背景", type: "image" },
    { name: "王座厅", url: "https://files.catbox.moe/4vblqw.png", category: "背景", type: "image" },
    { name: "卧室", url: "https://files.catbox.moe/7fmmer.png", category: "背景", type: "image" },
    { name: "卧室晚上", url: "https://files.catbox.moe/emuhml.png", category: "背景", type: "image" },
    { name: "夜晚庄园会客厅", url: "https://files.catbox.moe/s0lzku.png", category: "背景", type: "image" },
    { name: "夜晚庄园门口", url: "https://files.catbox.moe/t30w1k.png", category: "背景", type: "image" },
    { name: "阴暗大门", url: "https://files.catbox.moe/7ld24b.png", category: "背景", type: "image" },
    { name: "营地", url: "https://files.catbox.moe/uirewc.png", category: "背景", type: "image" },
    { name: "营地床铺", url: "https://files.catbox.moe/al1jxf.png", category: "背景", type: "image" },
    { name: "营地晚上", url: "https://files.catbox.moe/y7ein8.png", category: "背景", type: "image" },
    { name: "庄园餐厅", url: "https://files.catbox.moe/sg26no.png", category: "背景", type: "image" },
    { name: "庄园房间", url: "https://files.catbox.moe/87omvd.png", category: "背景", type: "image" },
    { name: "庄园会客厅", url: "https://files.catbox.moe/5d1l3p.png", category: "背景", type: "image" },
    { name: "庄园门口", url: "https://files.catbox.moe/2ne9c0.png", category: "背景", type: "image" },
    { name: "庄园室内花园", url: "https://files.catbox.moe/msn1g0.png", category: "背景", type: "image" },
    { name: "庄园书库", url: "https://files.catbox.moe/06iof0.png", category: "背景", type: "image" },
    { name: "庄园走廊", url: "https://files.catbox.moe/nyeozy.png", category: "背景", type: "image" },
    { name: "Kiss全裸-wink吐舌", url: "https://files.catbox.moe/zvpw3h.png", category: "CG", type: "image" },
    { name: "Kiss全裸-闭眼咧嘴笑", url: "https://files.catbox.moe/eopylo.png", category: "CG", type: "image" },
    { name: "Kiss全裸-激烈亲吻", url: "https://files.catbox.moe/snrr2h.png", category: "CG", type: "image" },
    { name: "Kiss全裸-惊讶", url: "https://files.catbox.moe/1z7v55.png", category: "CG", type: "image" },
    { name: "Kiss全裸-亲吻", url: "https://files.catbox.moe/kic175.png", category: "CG", type: "image" },
    { name: "Kiss全裸-微笑", url: "https://files.catbox.moe/6snfuk.png", category: "CG", type: "image" },
    { name: "Kiss全裸-心形瞳孔吐舌", url: "https://files.catbox.moe/f30kbc.png", category: "CG", type: "image" },
    { name: "Kiss全裸-睁眼抿嘴", url: "https://files.catbox.moe/m6hyuh.png", category: "CG", type: "image" },
    { name: "Kiss着衣-闭眼嘟嘴", url: "https://files.catbox.moe/a68y5p.png", category: "CG", type: "image" },
    { name: "Kiss着衣-闭眼抿嘴", url: "https://files.catbox.moe/vm3uj3.png", category: "CG", type: "image" },
    { name: "Kiss着衣-惊讶", url: "https://files.catbox.moe/3i4q04.png", category: "CG", type: "image" },
    { name: "Kiss着衣-亲吻", url: "https://files.catbox.moe/q28gz4.png", category: "CG", type: "image" },
    { name: "Kiss着衣-无高光", url: "https://files.catbox.moe/njly8i.png", category: "CG", type: "image" },
    { name: "Kiss着衣-睁眼嘟嘴", url: "https://files.catbox.moe/wz63bi.png", category: "CG", type: "image" },
    { name: "Kiss着衣-睁眼咧嘴笑", url: "https://files.catbox.moe/5otlm5.png", category: "CG", type: "image" },
    { name: "Kiss着衣-睁眼微笑", url: "https://files.catbox.moe/snb9w9.png", category: "CG", type: "image" },
    { name: "乳交-惊讶", url: "https://files.catbox.moe/sec9ke.png", category: "CG", type: "image" },
    { name: "乳交-满脸精液", url: "https://files.catbox.moe/ee7s4m.png", category: "CG", type: "image" },
    { name: "乳交-满脸精液闭眼舔舐龟头", url: "https://files.catbox.moe/pwnu0p.png", category: "CG", type: "image" },
    { name: "乳交-抿嘴笑", url: "https://files.catbox.moe/d16gyo.png", category: "CG", type: "image" },
    { name: "乳交-微笑上下乳交", url: "https://files.catbox.moe/8tt5cx.png", category: "CG", type: "image" },
    { name: "乳交-眼冒爱心满脸精液", url: "https://files.catbox.moe/5hddcc.png", category: "CG", type: "image" },
    { name: "乳交-眼冒爱心满脸精液咧嘴笑", url: "https://files.catbox.moe/xihgql.png", category: "CG", type: "image" },
    { name: "乳交-眼冒爱心上下乳交舔舐龟头", url: "https://files.catbox.moe/mfob6a.png", category: "CG", type: "image" },
    { name: "乳交-眼冒爱心射精上下乳交", url: "https://files.catbox.moe/5etexr.png", category: "CG", type: "image" },
    { name: "乳交-眼冒心形上下乳交", url: "https://files.catbox.moe/3a9gi1.png", category: "CG", type: "image" },
    { name: "乳交-wink对龟头哈气", url: "https://files.catbox.moe/phzm52.png", category: "CG", type: "image" },
    { name: "乳交-wink舔舐龟头", url: "https://files.catbox.moe/x8c9r0.png", category: "CG", type: "image" },
    { name: "乳交-闭眼舔舐龟头上下乳交", url: "https://files.catbox.moe/m3fghf.png", category: "CG", type: "image" },
    { name: "乳交-嘟嘴", url: "https://files.catbox.moe/ft6spt.png", category: "CG", type: "image" },
    { name: "乳交-对龟头哈气", url: "https://files.catbox.moe/8hyxry.png", category: "CG", type: "image" },
    { name: "乳交-近景", url: "https://files.catbox.moe/ql9k8s.png", category: "CG", type: "image" },
    { name: "骑乘位阶段12-插入", url: "https://files.catbox.moe/k5c6fb.png", category: "CG", type: "image" },
    { name: "骑乘位阶段12-插入破处", url: "https://files.catbox.moe/dii9nh.png", category: "CG", type: "image" },
    { name: "骑乘位阶段12-抽插", url: "https://files.catbox.moe/xskj6g.png", category: "CG", type: "image" },
    { name: "骑乘位阶段12-激烈抽插", url: "https://files.catbox.moe/7a3oa7.png", category: "CG", type: "image" },
    { name: "骑乘位阶段12-素股微笑", url: "https://files.catbox.moe/jmyndt.png", category: "CG", type: "image" },
    { name: "骑乘位阶段12-素股张嘴", url: "https://files.catbox.moe/c6aaw6.png", category: "CG", type: "image" },
    { name: "骑乘位阶段12-中出", url: "https://files.catbox.moe/pnihqh.png", category: "CG", type: "image" },
    { name: "骑乘位阶段12-中出后温存", url: "https://files.catbox.moe/oy0nez.png", category: "CG", type: "image" },
    { name: "骑乘位阶段34-抱头插入", url: "https://files.catbox.moe/hn9a2w.png", category: "CG", type: "image" },
    { name: "骑乘位阶段34-抱头抽插", url: "https://files.catbox.moe/nplj5o.png", category: "CG", type: "image" },
    { name: "骑乘位阶段34-抱头抽插咬牙", url: "https://files.catbox.moe/f57x9e.png", category: "CG", type: "image" },
    { name: "骑乘位阶段34-插入", url: "https://files.catbox.moe/0crgcj.png", category: "CG", type: "image" },
    { name: "骑乘位阶段34-揉胸揉阴蒂插入", url: "https://files.catbox.moe/iq4wxr.png", category: "CG", type: "image" },
    { name: "骑乘位阶段34-揉胸揉阴蒂嫌弃插入", url: "https://files.catbox.moe/mnutnj.png", category: "CG", type: "image" },
    { name: "骑乘位阶段34-素股", url: "https://files.catbox.moe/jl2f3v.png", category: "CG", type: "image" },
    { name: "骑乘位阶段34-中出", url: "https://files.catbox.moe/j2f8bc.png", category: "CG", type: "image" },
    { name: "骑乘位阶段34-中出后温存", url: "https://files.catbox.moe/u4jc7b.png", category: "CG", type: "image" },
    { name: "骑乘位情趣内衣-素股", url: "https://files.catbox.moe/hse095.png", category: "CG", type: "image" },
    { name: "骑乘位情趣内衣-素股嘟嘴", url: "https://files.catbox.moe/mlpib9.png", category: "CG", type: "image" },
    { name: "骑乘位情趣内衣-素股害羞", url: "https://files.catbox.moe/c0h3jq.png", category: "CG", type: "image" },
    { name: "骑乘位情趣内衣-素股气呼呼", url: "https://files.catbox.moe/js3k50.png", category: "CG", type: "image" },
    { name: "骑乘位情趣内衣-素股咬牙", url: "https://files.catbox.moe/090601.png", category: "CG", type: "image" },
    { name: "骑乘位情趣内衣-中出后害羞", url: "https://files.catbox.moe/vjupbz.png", category: "CG", type: "image" },
    { name: "骑乘位情趣内衣-中出后温存", url: "https://files.catbox.moe/cdpegn.png", category: "CG", type: "image" },
    { name: "骑乘位情趣内衣-插入", url: "https://files.catbox.moe/owrda8.png", category: "CG", type: "image" },
    { name: "骑乘位情趣内衣-抽插", url: "https://files.catbox.moe/svv08p.png", category: "CG", type: "image" },
    { name: "骑乘位情趣内衣-抽插2", url: "https://files.catbox.moe/03h1yz.png", category: "CG", type: "image" },
    { name: "骑乘位情趣内衣-抽插高潮中出", url: "https://files.catbox.moe/wnqliu.png", category: "CG", type: "image" },
    { name: "骑乘位情趣内衣-抽插娇喘", url: "https://files.catbox.moe/x1obo7.png", category: "CG", type: "image" },
    { name: "骑乘位情趣内衣-抽插惊讶", url: "https://files.catbox.moe/jcsxco.png", category: "CG", type: "image" },
    { name: "骑乘位情趣内衣-抽插眯眼", url: "https://files.catbox.moe/f6kbew.png", category: "CG", type: "image" },
    { name: "骑乘位情趣内衣-抽插咬牙", url: "https://files.catbox.moe/5zfgnj.png", category: "CG", type: "image" },
    { name: "床上后背位-插入", url: "https://files.catbox.moe/3f8hkn.png", category: "CG", type: "image" },
    { name: "床上后背位-射精翻白眼吐舌", url: "https://files.catbox.moe/ps7wxk.png", category: "CG", type: "image" },
    { name: "床上后背位-射精后翻白眼高潮", url: "https://files.catbox.moe/22n1v8.png", category: "CG", type: "image" },
    { name: "床上后背位-射精后翻白眼剧烈高潮", url: "https://files.catbox.moe/3s29nz.png", category: "CG", type: "image" },
    { name: "床上后背位-射精后翻白眼流泪", url: "https://files.catbox.moe/anqy6t.png", category: "CG", type: "image" },
    { name: "床上后背位-射精后高潮", url: "https://files.catbox.moe/1vj1ub.png", category: "CG", type: "image" },
    { name: "床上后背位-射精后剧烈高潮吐舌", url: "https://files.catbox.moe/24yv1q.png", category: "CG", type: "image" },
    { name: "床上后背位-射精后睁大眼流泪", url: "https://files.catbox.moe/87z8ye.png", category: "CG", type: "image" },
    { name: "床上后背位-射精剧烈高潮翻白眼", url: "https://files.catbox.moe/dsdzw1.png", category: "CG", type: "image" },
    { name: "地板后背位-闭嘴", url: "https://files.catbox.moe/7n7mox.png", category: "CG", type: "image" },
    { name: "地板后背位-插入", url: "https://files.catbox.moe/lx6b98.png", category: "CG", type: "image" },
    { name: "地板后背位-插入翻白眼吐舌", url: "https://files.catbox.moe/wpfzoz.png", category: "CG", type: "image" },
    { name: "地板后背位-插入预备闭嘴", url: "https://files.catbox.moe/n836u6.png", category: "CG", type: "image" },
    { name: "地板后背位-插入预备张嘴", url: "https://files.catbox.moe/xrpigt.png", category: "CG", type: "image" },
    { name: "地板后背位-等待", url: "https://files.catbox.moe/4nefhd.png", category: "CG", type: "image" },
    { name: "地板后背位-等待舔嘴唇", url: "https://files.catbox.moe/j32anl.png", category: "CG", type: "image" },
    { name: "地板后背位-等待睁大眼", url: "https://files.catbox.moe/b9q30c.png", category: "CG", type: "image" },
    { name: "地板后背位-射精翻白眼", url: "https://files.catbox.moe/w6tpj6.png", category: "CG", type: "image" },
    { name: "地板后背位-射精后", url: "https://files.catbox.moe/yujbr7.png", category: "CG", type: "image" },
    { name: "地板后背位-射精后翻白眼吐舌", url: "https://files.catbox.moe/5tmues.png", category: "CG", type: "image" },
    { name: "趴式后背位-抽插心形瞳孔吐舌", url: "https://files.catbox.moe/a86uik.png", category: "CG", type: "image" },
    { name: "趴式后背位-抽插心形瞳孔吐舌中出", url: "https://files.catbox.moe/s3yet2.png", category: "CG", type: "image" },
    { name: "趴式后背位-抽插心形瞳孔中出", url: "https://files.catbox.moe/kk2gir.png", category: "CG", type: "image" },
    { name: "趴式后背位-抽插张嘴", url: "https://files.catbox.moe/0v0ap9.png", category: "CG", type: "image" },
    { name: "趴式后背位-抽插睁单眼闭嘴", url: "https://files.catbox.moe/ca93w2.png", category: "CG", type: "image" },
    { name: "趴式后背位-中出往后看", url: "https://files.catbox.moe/oj5uan.png", category: "CG", type: "image" },
    { name: "趴式后背位-插入睁单眼闭嘴", url: "https://files.catbox.moe/984ara.png", category: "CG", type: "image" },
    { name: "趴式后背位-抽插闭嘴", url: "https://files.catbox.moe/m4ox30.png", category: "CG", type: "image" },
    { name: "趴式后背位-抽插快感", url: "https://files.catbox.moe/fchm8c.png", category: "CG", type: "image" },
    { name: "趴式后背位-抽插心形瞳孔", url: "https://files.catbox.moe/o6p1h5.png", category: "CG", type: "image" },
    { name: "趴式后背位-抽插心形瞳孔2", url: "https://files.catbox.moe/w8uw2y.png", category: "CG", type: "image" },
    { name: "趴式后背位-抽插心形瞳孔闭嘴", url: "https://files.catbox.moe/2nqn2p.png", category: "CG", type: "image" },
    { name: "趴式后背位-抽插心形瞳孔翻白眼中出", url: "https://files.catbox.moe/njv63z.png", category: "CG", type: "image" },
    { name: "侧入位-翻白眼吐舌心形瞳孔抽插射精", url: "https://files.catbox.moe/qovu68.png", category: "CG", type: "image" },
    { name: "侧入位-翻白眼吐舌心形眼抽插射满身", url: "https://files.catbox.moe/2e4q0u.png", category: "CG", type: "image" },
    { name: "侧入位-翻白眼吐舌心形眼抽插射满身中出", url: "https://files.catbox.moe/psnu9z.png", category: "CG", type: "image" },
    { name: "侧入位-翻白眼心形眼抽插射满身高潮", url: "https://files.catbox.moe/ylopcn.png", category: "CG", type: "image" },
    { name: "侧入位-往后看咬牙未插入精液溢出", url: "https://files.catbox.moe/r4439a.png", category: "CG", type: "image" },
    { name: "侧入位-无高光翻白眼吐舌未插入精液溢出", url: "https://files.catbox.moe/utzpsw.png", category: "CG", type: "image" },
    { name: "侧入位-心形眼吐舌高潮射满身抽插", url: "https://files.catbox.moe/8ry8bs.png", category: "CG", type: "image" },
    { name: "侧入位-咬牙往后看插入前", url: "https://files.catbox.moe/zltkn5.png", category: "CG", type: "image" },
    { name: "侧入位-咬牙笑往后看插入前", url: "https://files.catbox.moe/ob6uu9.png", category: "CG", type: "image" },
    { name: "侧入位-睁大眼惊讶往后看射满身未插入", url: "https://files.catbox.moe/hup08d.png", category: "CG", type: "image" },
    { name: "侧入位-睁单眼插入", url: "https://files.catbox.moe/vba43b.png", category: "CG", type: "image" },
    { name: "侧入位-睁单眼抽插", url: "https://files.catbox.moe/3zzryd.png", category: "CG", type: "image" },
    { name: "侧入位-睁单眼抽插精液溢出", url: "https://files.catbox.moe/e6jqjl.png", category: "CG", type: "image" },
    { name: "侧入位-闭眼抽插精液溢出", url: "https://files.catbox.moe/lv29gu.png", category: "CG", type: "image" },
    { name: "侧入位-闭眼高潮射身上未插入", url: "https://files.catbox.moe/co2o1g.png", category: "CG", type: "image" },
    { name: "侧入位-闭眼高潮未插入", url: "https://files.catbox.moe/mqhyso.png", category: "CG", type: "image" },
    { name: "侧入位-闭眼咬牙中出", url: "https://files.catbox.moe/kqu0sv.png", category: "CG", type: "image" },
    { name: "侧入位-抽插射满身闭眼咬牙中出", url: "https://files.catbox.moe/8sertn.png", category: "CG", type: "image" },
    { name: "侧入位-睁眼往后看舔嘴唇未插入射满身", url: "https://files.catbox.moe/ea7tjd.png", category: "CG", type: "image" },
    { name: "侧入位-睁眼往后看未插入射满身", url: "https://files.catbox.moe/imbo8o.png", category: "CG", type: "image" },
    { name: "侧入位-睁眼往后看笑抽插", url: "https://files.catbox.moe/ih55mj.png", category: "CG", type: "image" },
    { name: "侧入位-睁眼往后看笑猫嘴精液溢出", url: "https://files.catbox.moe/il4cxl.png", category: "CG", type: "image" },
    { name: "侧入位-睁单眼射满身抽插", url: "https://files.catbox.moe/yrg1st.png", category: "CG", type: "image" },
    { name: "侧入位-睁单眼往后看未插入射满身", url: "https://files.catbox.moe/dgrr3a.png", category: "CG", type: "image" },
    { name: "侧入位-睁单眼微笑插入", url: "https://files.catbox.moe/c6isbd.png", category: "CG", type: "image" },
    { name: "侧入位-睁单眼心形瞳孔抽插精液溢出", url: "https://files.catbox.moe/kyg00u.png", category: "CG", type: "image" },
    { name: "侧入位-睁眼往后看抽插精液溢出", url: "https://files.catbox.moe/2gyetw.png", category: "CG", type: "image" },
    { name: "侧入位-睁眼往后看猫唇未插入射满身", url: "https://files.catbox.moe/tgcfzx.png", category: "CG", type: "image" },
    { name: "正常位-振动棒振动", url: "https://files.catbox.moe/3oumcw.png", category: "CG", type: "image" },
    { name: "正常位-中出后", url: "https://files.catbox.moe/rx62oq.png", category: "CG", type: "image" },
    { name: "正常位-掰穴", url: "https://files.catbox.moe/8ycxeb.png", category: "CG", type: "image" },
    { name: "正常位-抽插", url: "https://files.catbox.moe/b3d2fk.png", category: "CG", type: "image" },
    { name: "正常位-高潮中出", url: "https://files.catbox.moe/iiawfp.png", category: "CG", type: "image" },
    { name: "正常位-射精在脚上后", url: "https://files.catbox.moe/o3f7of.png", category: "CG", type: "image" },
    { name: "正常位-振动棒插入", url: "https://files.catbox.moe/3tboew.png", category: "CG", type: "image" },
    { name: "正常位-振动棒插入撸管", url: "https://files.catbox.moe/20fhqf.png", category: "CG", type: "image" },
    { name: "正常位-振动棒插入撸管射精", url: "https://files.catbox.moe/caa8fi.png", category: "CG", type: "image" },
    { name: "骑乘位女仆装-表达爱意拔出", url: "https://files.catbox.moe/zd8307.png", category: "CG", type: "image" },
    { name: "骑乘位女仆装-表达爱意双手撑着抽插", url: "https://files.catbox.moe/42lcpt.png", category: "CG", type: "image" },
    { name: "骑乘位女仆装-颤抖拔出", url: "https://files.catbox.moe/az8b9d.png", category: "CG", type: "image" },
    { name: "骑乘位女仆装-单手捂嘴单手撑着抽插", url: "https://files.catbox.moe/13qmy7.png", category: "CG", type: "image" },
    { name: "骑乘位女仆装-嘟嘴颤抖拔出手撑着", url: "https://files.catbox.moe/xxwxje.png", category: "CG", type: "image" },
    { name: "骑乘位女仆装-嘟嘴抽插", url: "https://files.catbox.moe/4y5jxl.png", category: "CG", type: "image" },
    { name: "骑乘位女仆装-翻白眼咬牙精液溢出抽插", url: "https://files.catbox.moe/m3s86f.png", category: "CG", type: "image" },
    { name: "骑乘位女仆装-害羞单手捂嘴单手撑着抽插", url: "https://files.catbox.moe/irlh5q.png", category: "CG", type: "image" },
    { name: "骑乘位女仆装-惊讶看外面插入", url: "https://files.catbox.moe/70u90l.png", category: "CG", type: "image" },
    { name: "骑乘位女仆装-咬牙抽插", url: "https://files.catbox.moe/r717pn.png", category: "CG", type: "image" },
    { name: "骑乘位女仆装-咬牙激烈抽插", url: "https://files.catbox.moe/gq9bz5.png", category: "CG", type: "image" },
    { name: "骑乘位女仆装-张口闭眼中出", url: "https://files.catbox.moe/9l7irr.png", category: "CG", type: "image" },
    { name: "骑乘位女仆装-张嘴闭眼中出", url: "https://files.catbox.moe/dkkhsf.png", category: "CG", type: "image" },
    { name: "骑乘位女仆装-张嘴抽插", url: "https://files.catbox.moe/dca7wa.png", category: "CG", type: "image" },
    { name: "骑乘位女仆装-张嘴害羞激烈抽插", url: "https://files.catbox.moe/6io8cs.png", category: "CG", type: "image" },
    { name: "骑乘位女仆装-张嘴激烈抽插", url: "https://files.catbox.moe/hrs1g6.png", category: "CG", type: "image" },
    { name: "骑乘位女仆装-张嘴精液溢出", url: "https://files.catbox.moe/6n2w25.png", category: "CG", type: "image" },
    { name: "骑乘位女仆装-中出后拔出", url: "https://files.catbox.moe/ern82i.png", category: "CG", type: "image" },
    { name: "骑乘位女仆装-中出后自己爱抚乳头和阴蒂", url: "https://files.catbox.moe/rv5660.png", category: "CG", type: "image" },
    { name: "骑乘位女仆装-抱头插入", url: "https://files.catbox.moe/tjn869.png", category: "CG", type: "image" },
    { name: "女仆装-半开门探出抿嘴", url: "https://files.catbox.moe/c8co16.png", category: "CG", type: "image" },
    { name: "女仆装-半开门探出身体被抓住肩膀往后看惊讶", url: "https://files.catbox.moe/kowxno.png", category: "CG", type: "image" },
    { name: "女仆装-半开门探出身体被抓住肩膀张嘴笑", url: "https://files.catbox.moe/ie94ge.png", category: "CG", type: "image" },
    { name: "女仆装-半开门探出身体惊讶", url: "https://files.catbox.moe/pz01s1.png", category: "CG", type: "image" },
    { name: "女仆装-半开门探出身体露齿笑", url: "https://files.catbox.moe/mupl8t.png", category: "CG", type: "image" },
    { name: "女仆装-半开门探出身体抿嘴", url: "https://files.catbox.moe/0zd9m0.png", category: "CG", type: "image" },
    { name: "女仆装-半开门探出身体说话", url: "https://files.catbox.moe/zzjg7n.png", category: "CG", type: "image" },
    { name: "女仆装-半开门探出身体往上看露齿笑", url: "https://files.catbox.moe/gbjemd.png", category: "CG", type: "image" },
    { name: "女仆装-半开门探出身体小张嘴", url: "https://files.catbox.moe/svbg8n.png", category: "CG", type: "image" },
    { name: "女仆装-半开门探出身体笑", url: "https://files.catbox.moe/czah4z.png", category: "CG", type: "image" },
    { name: "女仆装-半开门探出身体眼神躲闪", url: "https://files.catbox.moe/paffmz.png", category: "CG", type: "image" },
    { name: "女仆装-半开门探出身体眼神躲闪害羞", url: "https://files.catbox.moe/5myhfa.png", category: "CG", type: "image" },
    { name: "女仆装-半开门探出身体眼神躲闪惊讶", url: "https://files.catbox.moe/9huleh.png", category: "CG", type: "image" },
    { name: "女仆装-半开门探出身体用手臂遮住乳头闭眼张嘴", url: "https://files.catbox.moe/y7e0q8.png", category: "CG", type: "image" },
    { name: "女仆装-半开门探出身体用手臂遮住乳头小张嘴", url: "https://files.catbox.moe/fesnvu.png", category: "CG", type: "image" },
    { name: "女仆装-半开门探出身体用手臂遮住乳头笑", url: "https://files.catbox.moe/brnrgy.png", category: "CG", type: "image" },
    { name: "女仆装-半开门探出身体张嘴笑", url: "https://files.catbox.moe/6imv67.png", category: "CG", type: "image" },
    { name: "女仆装-半开门探出身体嘴部阴毛向上看", url: "https://files.catbox.moe/arwh1y.png", category: "CG", type: "image" },
    { name: "女仆装-半开门探出身体嘴部阴毛眼神躲闪", url: "https://files.catbox.moe/h98dew.png", category: "CG", type: "image" },
    { name: "女仆装-半开门探出身体嘴部阴毛张嘴", url: "https://files.catbox.moe/u00wvo.png", category: "CG", type: "image" },
    { name: "女仆装早晨-半开门探出身体小张嘴笑", url: "https://files.catbox.moe/jmpcry.png", category: "CG", type: "image" },
    { name: "女仆装早晨-半开门探出身体心形眼颤抖", url: "https://files.catbox.moe/rogbgv.png", category: "CG", type: "image" },
    { name: "女仆装早晨-半开门探出身体心形眼翻白眼高潮", url: "https://files.catbox.moe/57jwoa.png", category: "CG", type: "image" },
    { name: "女仆装早晨-半开门探出身体眼神躲闪", url: "https://files.catbox.moe/7qzrld.png", category: "CG", type: "image" },
    { name: "女仆装早晨-半开门探出身体眼神躲闪嘟嘴", url: "https://files.catbox.moe/baxz7a.png", category: "CG", type: "image" },
    { name: "女仆装早晨-半开门探出身体眼神躲闪小张嘴", url: "https://files.catbox.moe/3pa9n9.png", category: "CG", type: "image" },
    { name: "女仆装早晨-半开门探出身体眼神躲闪张嘴笑", url: "https://files.catbox.moe/zctz14.png", category: "CG", type: "image" },
    { name: "女仆装早晨-半开门探出身体张嘴笑", url: "https://files.catbox.moe/iftpio.png", category: "CG", type: "image" },
    { name: "女仆装早晨-半开门探出身体闭眼张嘴高潮", url: "https://files.catbox.moe/9q2ewq.png", category: "CG", type: "image" },
    { name: "女仆装早晨-半开门探出身体闭嘴", url: "https://files.catbox.moe/pjgsz1.png", category: "CG", type: "image" },
    { name: "女仆装早晨-半开门探出身体咧嘴笑", url: "https://files.catbox.moe/odqh8t.png", category: "CG", type: "image" },
    { name: "女仆装早晨-半开门探出身体抿嘴", url: "https://files.catbox.moe/utj509.png", category: "CG", type: "image" },
    { name: "女仆装早晨-半开门探出身体抿嘴皱眉", url: "https://files.catbox.moe/rivxke.png", category: "CG", type: "image" },
    { name: "女仆装早晨-半开门探出身体撇嘴", url: "https://files.catbox.moe/jv7d6b.png", category: "CG", type: "image" },
    { name: "女仆装早晨-半开门探出身体平静", url: "https://files.catbox.moe/exjh9u.png", category: "CG", type: "image" },
    { name: "女仆装早晨-半开门探出身体微笑", url: "https://files.catbox.moe/0pbp5m.png", category: "CG", type: "image" },
    { name: "早晨-半开门探出身体全裸惊讶用手臂遮住乳头", url: "https://files.catbox.moe/uvuvd4.png", category: "CG", type: "image" },
    { name: "早晨-半开门探出身体全裸眯眼", url: "https://files.catbox.moe/6sowym.png", category: "CG", type: "image" },
    { name: "浴室-开门露出乳头拔出手指淫液拉丝", url: "https://files.catbox.moe/t6zoeu.png", category: "CG", type: "image" },
    { name: "浴室-开门露出乳头被拽乳头往后看张嘴被抠小穴", url: "https://files.catbox.moe/qmqlhf.png", category: "CG", type: "image" },
    { name: "浴室-开门露出乳头被拽乳头往后看张嘴被抠小穴高潮", url: "https://files.catbox.moe/aim2j3.png", category: "CG", type: "image" },
    { name: "浴室-半开门探出上半身露出乳头闭眼抿嘴", url: "https://files.catbox.moe/hxjcfv.png", category: "CG", type: "image" },
    { name: "浴室-半开门探出上半身露出乳头张嘴", url: "https://files.catbox.moe/imzh14.png", category: "CG", type: "image" },
    { name: "浴室-半开门探出上半身抿嘴抽插", url: "https://files.catbox.moe/3evydi.png", category: "CG", type: "image" },
    { name: "浴室-半开门探出上半身撇嘴抽插", url: "https://files.catbox.moe/9jvxi7.png", category: "CG", type: "image" },
    { name: "浴室-半开门探出上半身手臂遮住乳头抿嘴", url: "https://files.catbox.moe/5q58z4.png", category: "CG", type: "image" },
    { name: "浴室-半开门探出上半身手臂遮住乳头笑", url: "https://files.catbox.moe/6mc1y8.png", category: "CG", type: "image" },
    { name: "浴室-半开门探出上半身手臂遮住乳头眼神躲闪抿嘴", url: "https://files.catbox.moe/3nn7y3.png", category: "CG", type: "image" },
    { name: "浴室-半开门探出上半身心形眼咬牙抽插", url: "https://files.catbox.moe/shbyzx.png", category: "CG", type: "image" },
    { name: "浴室-半开门探出上半身张嘴抽插", url: "https://files.catbox.moe/i9mke8.png", category: "CG", type: "image" },
    { name: "浴室-半开门探出上半身张嘴娇喘心形眼翻白眼抽插", url: "https://files.catbox.moe/maji6k.png", category: "CG", type: "image" },
    { name: "浴室-半开门探出上半身张嘴眼神躲闪抽插", url: "https://files.catbox.moe/r0h8uk.png", category: "CG", type: "image" },
    { name: "浴室透视-隔着门露出乳头心形眼翻白眼张嘴抽插", url: "https://files.catbox.moe/eudvrq.png", category: "CG", type: "image" },
    { name: "浴室透视-隔着门露出乳头心形眼张嘴抽插", url: "https://files.catbox.moe/t182wb.png", category: "CG", type: "image" },
    { name: "浴室透视-隔着门露出乳头眼睛躲闪闭嘴被揉胸", url: "https://files.catbox.moe/3wfqnf.png", category: "CG", type: "image" },
    { name: "浴室透视-隔着门趴在门上", url: "https://files.catbox.moe/qukjca.png", category: "CG", type: "image" },
    { name: "浴室透视-隔着门全裸心形眼闭嘴往后看中出精液溢出", url: "https://files.catbox.moe/yyyueg.png", category: "CG", type: "image" },
    { name: "浴室透视-隔着门全裸心形眼翻白眼大张嘴吐舌淫叫抽插", url: "https://files.catbox.moe/8cjs4w.png", category: "CG", type: "image" },
    { name: "浴室透视-隔着门全裸心形眼翻白眼咬牙淫叫被拽乳头中出", url: "https://files.catbox.moe/e7rw43.png", category: "CG", type: "image" },
    { name: "浴室透视-隔着门全裸心形眼张嘴精液溢出肉棒打屁股", url: "https://files.catbox.moe/05f51t.png", category: "CG", type: "image" },
    { name: "浴室透视-隔着门全裸心形眼张嘴淫叫精液溢出抽插", url: "https://files.catbox.moe/ak536s.png", category: "CG", type: "image" },
    { name: "浴室透视-隔着门自己捂嘴露出乳头抽插", url: "https://files.catbox.moe/a2xok5.png", category: "CG", type: "image" },
    { name: "浴室透视-隔着门露出乳头被拽乳头往后看捂嘴被抠小穴", url: "https://files.catbox.moe/hpyfpf.png", category: "CG", type: "image" },
    { name: "浴室透视-隔着门露出乳头被拽乳头捂嘴", url: "https://files.catbox.moe/enwehz.png", category: "CG", type: "image" },
    { name: "浴室透视-隔着门露出乳头被拽乳头眼睛往后看闭嘴生气", url: "https://files.catbox.moe/w4bpx7.png", category: "CG", type: "image" },
    { name: "浴室透视-隔着门露出乳头被拽乳头眼神无光捂嘴被抠小穴", url: "https://files.catbox.moe/a69u8m.png", category: "CG", type: "image" },
    { name: "浴室透视-隔着门露出乳头闭眼张嘴抽插", url: "https://files.catbox.moe/7ll4ua.png", category: "CG", type: "image" },
    { name: "浴室透视-隔着门露出乳头惊讶往后看被揉胸", url: "https://files.catbox.moe/ayqtqd.png", category: "CG", type: "image" },
    { name: "浴室透视-隔着门露出乳头心形眼闭嘴抽插", url: "https://files.catbox.moe/yhb28g.png", category: "CG", type: "image" },
    { name: "浴室透视-隔着门露出乳头心形眼翻白眼大张嘴抽插", url: "https://files.catbox.moe/p4batn.png", category: "CG", type: "image" },
    { name: "浴室透视-隔着门露出乳头心形眼翻白眼大张嘴吐舌抽插", url: "https://files.catbox.moe/jmx6rc.png", category: "CG", type: "image" },
    { name: "浴室透视-半开门探出上半身露出乳头闭眼抿嘴", url: "https://files.catbox.moe/y4cbw8.png", category: "CG", type: "image" },
    { name: "浴室透视-半开门探出上半身露出乳头张嘴", url: "https://files.catbox.moe/gsd4n9.png", category: "CG", type: "image" },
    { name: "浴室透视-半开门探出上半身抿嘴抽插", url: "https://files.catbox.moe/tmwckb.png", category: "CG", type: "image" },
    { name: "浴室透视-半开门探出上半身撇嘴抽插", url: "https://files.catbox.moe/ilx312.png", category: "CG", type: "image" },
    { name: "浴室透视-半开门探出上半身手臂遮住乳头抿嘴", url: "https://files.catbox.moe/eb8xm2.png", category: "CG", type: "image" },
    { name: "浴室透视-半开门探出上半身手臂遮住乳头笑", url: "https://files.catbox.moe/7zmky5.png", category: "CG", type: "image" },
    { name: "浴室透视-半开门探出上半身手臂遮住乳头眼神躲闪抿嘴", url: "https://files.catbox.moe/u2p4i6.png", category: "CG", type: "image" },
    { name: "浴室透视-半开门探出上半身心形眼咬牙抽插", url: "https://files.catbox.moe/4h8qos.png", category: "CG", type: "image" },
    { name: "浴室透视-半开门探出上半身张嘴抽插", url: "https://files.catbox.moe/tha7xq.png", category: "CG", type: "image" },
    { name: "浴室透视-半开门探出上半身张嘴娇喘心形眼翻白眼抽插", url: "https://files.catbox.moe/taeuil.png", category: "CG", type: "image" },
    { name: "浴室透视-半开门探出上半身张嘴眼神躲闪抽插", url: "https://files.catbox.moe/un2r5m.png", category: "CG", type: "image" },
    { name: "常服-半开门探出上半身嘴角阴毛抿嘴眼神躲闪", url: "https://files.catbox.moe/740v4n.png", category: "CG", type: "image" },
    { name: "常服-半开门探出上半身嘴角阴毛撇嘴", url: "https://files.catbox.moe/co3muy.png", category: "CG", type: "image" },
    { name: "常服-半开门探出上半身嘴角阴毛笑", url: "https://files.catbox.moe/vttzut.png", category: "CG", type: "image" },
    { name: "常服-半开门探出上半身嘴角阴毛眼神躲闪", url: "https://files.catbox.moe/ra80of.png", category: "CG", type: "image" },
    { name: "常服-半开门探出上半身抿嘴", url: "https://files.catbox.moe/h06uxu.png", category: "CG", type: "image" },
    { name: "常服-半开门探出上半身抿嘴笑", url: "https://files.catbox.moe/30qkxr.png", category: "CG", type: "image" },
    { name: "常服-半开门探出上半身抿嘴笑往后看", url: "https://files.catbox.moe/8whuzk.png", category: "CG", type: "image" },
    { name: "常服-半开门探出上半身撇嘴往后看", url: "https://files.catbox.moe/g67sd2.png", category: "CG", type: "image" },
    { name: "常服-半开门探出上半身往后看小张嘴", url: "https://files.catbox.moe/r53uyx.png", category: "CG", type: "image" },
    { name: "常服-半开门探出上半身眼睛睁大惊讶", url: "https://files.catbox.moe/ckvcx4.png", category: "CG", type: "image" },
    { name: "常服-半开门探出上半身眼神躲闪", url: "https://files.catbox.moe/ydf9at.png", category: "CG", type: "image" },
    { name: "常服-半开门探出上半身嘴角阴毛", url: "https://files.catbox.moe/m84qww.png", category: "CG", type: "image" },
    { name: "常服-半开门探出上半身嘴角阴毛大张嘴闭眼", url: "https://files.catbox.moe/povo4b.png", category: "CG", type: "image" },
    { name: "常服-半开门探出上半身嘴角阴毛抿嘴", url: "https://files.catbox.moe/pg0qiy.png", category: "CG", type: "image" },
    { name: "常服-半开门探出上身闭眼闭嘴", url: "https://files.catbox.moe/uj2bmo.png", category: "CG", type: "image" },
    { name: "常服-半开门探出上身高兴", url: "https://files.catbox.moe/73bmg2.png", category: "CG", type: "image" },
    { name: "常服-半开门探出上身脸红", url: "https://files.catbox.moe/n4xjap.png", category: "CG", type: "image" },
    { name: "常服-半开门探出上身抿嘴", url: "https://files.catbox.moe/mbjos5.png", category: "CG", type: "image" },
    { name: "常服-半开门探出上身往上看小张嘴", url: "https://files.catbox.moe/67v582.png", category: "CG", type: "image" },
    { name: "常服-半开门探出上身往上看笑", url: "https://files.catbox.moe/yz5g5k.png", category: "CG", type: "image" },
    { name: "常服-半开门探出上身笑", url: "https://files.catbox.moe/knqqup.png", category: "CG", type: "image" },
    { name: "常服-半开门探出上身眼睛躲闪", url: "https://files.catbox.moe/l4ir9d.png", category: "CG", type: "image" },
    { name: "通用门外视角-铁门外无声", url: "https://files.catbox.moe/0eawea.png", category: "CG", type: "image" },
    { name: "通用门外视角-铁门外淫叫", url: "https://files.catbox.moe/d6zssj.png", category: "CG", type: "image" },
    { name: "通用门外视角-木门外无声", url: "https://files.catbox.moe/3p1ct9.png", category: "CG", type: "image" },
    { name: "常服透视-隔着门胸部露出张大嘴吐舌头抽插", url: "https://files.catbox.moe/bu6izc.png", category: "CG", type: "image" },
    { name: "常服透视-隔着门胸部露出张大嘴往后看抽插", url: "https://files.catbox.moe/2j5v65.png", category: "CG", type: "image" },
    { name: "常服透视-隔着门咬牙中出心形眼翻白眼", url: "https://files.catbox.moe/pvwe7z.png", category: "CG", type: "image" },
    { name: "常服透视-隔着门张大嘴娇喘插入", url: "https://files.catbox.moe/8389af.png", category: "CG", type: "image" },
    { name: "常服透视-隔着门张大嘴娇喘抽插心形眼", url: "https://files.catbox.moe/684n4l.png", category: "CG", type: "image" },
    { name: "常服透视-隔着门往后看惊讶肉棒顶着屁股", url: "https://files.catbox.moe/fvi2ez.png", category: "CG", type: "image" },
    { name: "常服透视-隔着门往后看撇嘴生气肉棒顶着屁股", url: "https://files.catbox.moe/xc9jq9.png", category: "CG", type: "image" },
    { name: "常服透视-隔着门心形眼中出后", url: "https://files.catbox.moe/rx3jxw.png", category: "CG", type: "image" },
    { name: "常服透视-隔着门胸部露出张大嘴抽插", url: "https://files.catbox.moe/pr6o0r.png", category: "CG", type: "image" },
    { name: "常服透视-半开门探出上半身抿嘴", url: "https://files.catbox.moe/ei03kv.png", category: "CG", type: "image" },
    { name: "常服透视-半开门探出上半身抿嘴笑往后看", url: "https://files.catbox.moe/g8yrul.png", category: "CG", type: "image" },
    { name: "常服透视-半开门探出上半身撇嘴往后看", url: "https://files.catbox.moe/9prqsd.png", category: "CG", type: "image" },
    { name: "常服透视-半开门探出上半身往后看小张嘴肉棒顶着屁股", url: "https://files.catbox.moe/f0fo7u.png", category: "CG", type: "image" },
    { name: "常服透视-半开门探出上半身眼睛睁大往后看肉棒顶着屁股", url: "https://files.catbox.moe/q6lf5v.png", category: "CG", type: "image" },
    { name: "常服透视-半开门探出上半身眼神躲闪小张嘴肉棒顶着屁股", url: "https://files.catbox.moe/o7zzmb.png", category: "CG", type: "image" },
    { name: "Hstatus-表底图", url: "https://files.catbox.moe/3jrv5v.png", category: "Hstatus", type: "image" },
    { name: "Hstatus-表表图", url: "https://files.catbox.moe/iaar1p.png", category: "Hstatus", type: "image" },
    { name: "Hstatus-表高光", url: "https://files.catbox.moe/e7e84g.png", category: "Hstatus", type: "image" },
    { name: "Hstatus-边框", url: "https://files.catbox.moe/lht9hm.png", category: "Hstatus", type: "image" },
    { name: "Hstatus-里底图", url: "https://files.catbox.moe/92wfb8.png", category: "Hstatus", type: "image" },
    { name: "Hstatus-里表图", url: "https://files.catbox.moe/lbxw3t.png", category: "Hstatus", type: "image" },
    { name: "Hstatus-里高光", url: "https://files.catbox.moe/dm2rck.png", category: "Hstatus", type: "image" },
    { name: "Hstatus-光标", url: "https://files.catbox.moe/dgdqmk.png", category: "Hstatus", type: "image" },
    { name: "Hstatus-退出按钮", url: "https://files.catbox.moe/fcyjir.png", category: "Hstatus", type: "image" },
    { name: "精液-胸-少", url: "https://files.catbox.moe/htr1dh.png", category: "Hstatus", type: "image" },
    { name: "精液-胸-多", url: "https://files.catbox.moe/sct15g.png", category: "Hstatus", type: "image" },
    { name: "精液-腹-少", url: "https://files.catbox.moe/1qk8mk.png", category: "Hstatus", type: "image" },
    { name: "精液-腹-多", url: "https://files.catbox.moe/iznrta.png", category: "Hstatus", type: "image" },
    { name: "精液-腿-少", url: "https://files.catbox.moe/j8g4g4.png", category: "Hstatus", type: "image" },
    { name: "精液-腿-多", url: "https://files.catbox.moe/ay6ljp.png", category: "Hstatus", type: "image" },
    { name: "子宫弹窗-0", url: "https://files.catbox.moe/q6u20q.png", category: "Hstatus", type: "image" },
    { name: "子宫弹窗-1", url: "https://files.catbox.moe/9nv2qy.png", category: "Hstatus", type: "image" },
    { name: "子宫弹窗-2", url: "https://files.catbox.moe/d166xy.png", category: "Hstatus", type: "image" },
    { name: "子宫弹窗-3", url: "https://files.catbox.moe/8blqgc.png", category: "Hstatus", type: "image" },
    { name: "子宫弹窗-4", url: "https://files.catbox.moe/p9r91i.png", category: "Hstatus", type: "image" },
    { name: "菜单托莉娜立绘-阶段1", url: "https://files.catbox.moe/xrfvzg.png", category: "系统", type: "image" },
    { name: "菜单托莉娜立绘-阶段2", url: "https://files.catbox.moe/md0p61.png", category: "系统", type: "image" },
    { name: "菜单托莉娜立绘-阶段3", url: "https://files.catbox.moe/5utwfz.png", category: "系统", type: "image" },
    { name: "菜单托莉娜立绘-阶段4", url: "https://files.catbox.moe/4ro2io.png", category: "系统", type: "image" },
    { name: "设置界面UI图标", url: "https://files.catbox.moe/dykagy.png", category: "系统", type: "image" },
    { name: "设置标签", url: "https://files.catbox.moe/3fc4yw.png", category: "系统", type: "image" },
    { name: "Hstatus界面UI图标", url: "https://files.catbox.moe/yayh3o.png", category: "系统", type: "image" },
    { name: "Hstatus标签", url: "https://files.catbox.moe/zj7251.png", category: "系统", type: "image" },
    { name: "地图界面UI图标", url: "https://files.catbox.moe/n3kdfi.png", category: "系统", type: "image" },
    { name: "地图标签", url: "https://files.catbox.moe/vpyzz7.png", category: "系统", type: "image" },
    { name: "历史界面UI图标", url: "https://files.catbox.moe/v0cbzh.png", category: "系统", type: "image" },
    { name: "历史标签", url: "https://files.catbox.moe/y9656v.png", category: "系统", type: "image" },
    { name: "存档界面UI图标", url: "https://files.catbox.moe/l143y2.png", category: "系统", type: "image" },
    { name: "存档标签", url: "https://files.catbox.moe/aiw7z8.png", category: "系统", type: "image" },
    { name: "堕落值条", url: "https://files.catbox.moe/fc42vd.png", category: "系统", type: "image" },
    { name: "性欲值条", url: "https://files.catbox.moe/g5wizu.png", category: "系统", type: "image" }
  ];

  // 名称 -> url 索引
  const nameIndex = new Map(preloadList.map(a => [a.name, a.url]));

  function getAsset(name) { return nameIndex.get(name) || null; }
  function getBackground(name) { return getAsset(name); }
  function getCG(group, cgName) {
    const direct = getAsset(group + '-' + cgName);
    if (direct) return direct;
    const prefix = group + '-';
    const groupItems = preloadList.filter(a => a.category === 'CG' && a.name.startsWith(prefix));
    if (groupItems.length) { groupItems.sort((a, b) => a.name.localeCompare(b.name)); return groupItems[0].url; }
    return null;
  }
  function getSprite(layer, key) {
    const node = tolinaSprites[layer];
    if (!node) return null;
    if (key == null) return node;
    return node[key] || null;
  }
  function getExpression(series, key) {
    const s = tolinaSprites.L3_expression && tolinaSprites.L3_expression[series];
    return (s && s[key]) || null;
  }
  function getRival(name) { return rivalMaleSprites[name] || null; }
  function getHstatus(key) { return hstatusAssets[key] || null; }
  function getCum(key) { return cumUrls[key] || null; }
  function getWombPopup(i) { return wombPopupUrls[i] || null; }
  function getUI(key) { return uiAssets[key] || null; }
  function getHstatusOutfit(outfit, stage) {
    const s = Math.min(4, Math.max(1, parseInt(stage, 10) || 1));
    const o = hstatusOutfits[outfit] || hstatusOutfits['常服'];
    let body, clothes;
    if (outfit === '女仆装' && o.body) {
      const band = (s <= 2) ? '1-2' : '3-4';
      body = o.body[band]; clothes = o.clothes[band];
    } else {
      body = hstatusBodyByStage[s]; clothes = o.clothes;
    }
    return { body: body || hstatusBodyByStage[1], clothes: clothes || hstatusOutfits['常服'].clothes };
  }
  function getMenuSprite(stage) {
    const s = Math.min(4, Math.max(1, parseInt(stage, 10) || 1));
    return menuSpriteByStage[s] || menuSpriteByStage[1];
  }
  function getTimeImage(key) { return timeImageMap[key] || null; }
  function getWeatherImage(key) { return weatherImageMap[key] || null; }

  window.妹神官_gameAssets = {
    tolinaSprites, rivalMaleSprites, hstatusAssets, cumUrls, wombPopupUrls,
    hstatusOutfits, hstatusBodyByStage, menuSpriteByStage, timeImageMap, weatherImageMap, uiAssets,
    preloadList,
    getAsset, getBackground, getCG, getSprite, getExpression, getRival,
    getHstatus, getCum, getWombPopup, getUI, getHstatusOutfit, getMenuSprite, getTimeImage, getWeatherImage,
  };
})();
